### ISSUE TITLE
GRN input format

### ISSUE THREAD

**Issue by JBreunig** [theislab/regvelo#16]
Congrats on an exciting package!  I've got the tutorial to run without issue.

How does one import the GRNs from SCENIC+ or Dictys for matched datasets?

**Comment by GilbertHan1011** [comment]
CellOracle's [output](https://morris-lab.github.io/CellOracle.documentation/tutorials/base_grn.html) appears to integrate seamlessly with this package.

**Comment by WWXkenmo** [comment]
Hey! thanks for interesting to our work. Sorry I am in vacation so may not response on time

Yes, assume you have a gene regulatory network learned from SCENIC+ or Dictys, please create a binary matrix ($$n_{g} \times n_{g}$$), with the same genes to your input spliced and unspliced readout ($$n_{c} \times n_{g}$$). In the case when row indicating regulators, column indicating targets, you can run model like this

```
rgvae = REGVELOVI(adata,W=W.T,regulators = TF_list,soft_constraint = False)
```

Please check the prelimary tutorial (https://github.com/theislab/regvelo/blob/main/docs/tutorial.ipynb) for more details

Many thanks,
Ken
